### ISSUE TITLE
PaymentData 모델 관련 문의

### ISSUE THREAD

**Issue by leslie97** [iamport/iamport_flutter#105]
안녕하세요.

PaymentData 예제를 보면서 결제관련 기능을 추가하고 있는데 문의드릴것이 있습니다.
이 git 예제에 있는 PaymentData의 key 값과 예제에서 PaymentData 모델을 자세히 보기 해서 들어간 portone 사이트의 key 값이 다릅니다.
예를들면 예제에서는 buyerTel로 되어 있는데 portOne 사이트의 key 값은 buyer_tel로 되어 있습니다.
어느 key 값을 사용해야 하는건가요?

**Comment by anymate98** [comment]
웹에서 실행되는 자바스크립트 sdk상의 파라미터는 buyer_tel이지만 iamport_flutter에서는 플러터의 네이밍 규칙을 따르기 위해 buyerTel로 설정했고 웹뷰 상에서 해당 파라미터가 buyer_tel로 다시 변환이 되는 구조입니다.

**Comment by leslie97** [comment]
> 

네.. 제가 예제를 잘못적용했었네요.
답변 감사드립니다.
