### ISSUE TITLE
지원하는 PG사 추가 건의

### ISSUE THREAD

**Issue by woogi-kang** [iamport/iamport_flutter#106]
안녕하세요! 좋은 라이브러리 만들어주셔서 감사합니다.
이번에 KSNET PG사로 아임포트 SDK 를 연동하려고하는데 웹에서는 지원하는 KSNET이 Flutter 모듈에는 목록에 없네요.

혹시 KSNET을 추가로 지원해주실수있으신가요?

**Comment by anymate98** [comment]
안녕하세요. 지원 목록에 추가가 안되어 있기는 하나 지금도 ksnet으로 결제를 하실 수 있으니 참고 부탁드립니다.

**Comment by woogi-kang** [comment]
<img width="557" alt="스크린샷 2023-06-07 오후 6 02 04" src="https://github.com/iamport/iamport_flutter/assets/70678014/8dcfa1f8-3f94-439d-8994-66f53f94fb0e">

안녕하세요 @anymate98 님 빠른 답변 감사드립니다. 
말씀하신대로 ksnet으로 연동을 시도했는데 Iamport 열자마자 callback 으로
F500
결제 창 호출에 실패하였습니다. 스토어 정보를 조회하는데 실패하였습니다. 
위의 오류가 발생하고있습니다. 혹시 연동하는 데에 있어 제가 잘못한 부분이 있을까요?

**Comment by anymate98** [comment]
userCode는 결제연동 메뉴 우측상단의 내 식별코드->가맹점식별코드를 사용하시면 됩니다.

**Comment by woogi-kang** [comment]
@anymate98 해결되었습니다 감사합니다!
