### ISSUE TITLE
uni_link library의 버전업을 요청드립니다.

### ISSUE THREAD

**Issue by whatamelon** [iamport/iamport_flutter#11]
현재 해당 라이브러리의 버전은 0.4.0이고, iamport 라이브러리에서 참조하는 버전은 0.2.0 입니다.
따라서 최신 라이브러리 버전으로 업그레이드 부탁드립니다.

항상 잘 사용하고 있습니다. 좋은 라이브러리 감사합니다 XD

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

혹시 버전 업이 되지 않아 동작에 문제가 발생하고 계시는 부분이 있으실까요?
그렇다면 시급하게 버전을 업데이트하고, 그렇지 않다면 다음 버전때 함께 반영하고자 합니다.

감사합니다.

**Comment by whatamelon** [comment]
넵 다음 버전때 함께 반영해주시면 감사하겠습니다^^

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

말씀하신대로 uni_links 패키지의 버전을 0.2.0에서 0.4.0으로 업데이트 하여
iamport_flutter v0.9.12에 반영하였으니 확인 부탁드립니다.

- [버전정보](https://github.com/iamport/iamport_flutter/blob/master/CHANGELOG.md)
- [pubspec.yaml](https://github.com/iamport/iamport_flutter/blob/master/pubspec.yaml)

감사합니다.

**Comment by whatamelon** [comment]
넵 감사합니다!
