### ISSUE TITLE
PaymentData Bypass 관련 문의

### ISSUE THREAD

**Issue by yeajeanie** [iamport/iamport_flutter#114]
안녕하세요,

현금영수증 발행 불가하게 하도록
JS SDK 의 `criPsblYn: "N"` 와 같은 기능을 어떻게 넣을 수 있는지 문의드립니다.
`Bypass(cashReceiptType: String?)` 으로 가능하다면 해당 파라미터에 어떤 값이 들어가야하는지 모호하여 enum 처리해주시거나 문서 / 코드 주석에 타입을 정리해주시면 좋을 것 같습니다.

감사합니다.

**Comment by anymate98** [comment]
해당 파라미터 추가해서 배포했습니다. 또한 코드상에 주석으로 사용할 수 있는 값도 표기했으니 확인 부탁드립니다.
