### ISSUE TITLE
Webview initial loading issue

### ISSUE THREAD

**Issue by whatamelon** [iamport/iamport_flutter#12]
아임포트 웹뷰에 들어갔을때, 무한 로딩이 발생하는 이슈가 있습니다.
특정상황에 발생하는 것 같지는 않고, 어쩌다 한 번 낮은 확률로 발생합니다.

https://drive.google.com/file/d/11xvsuuOQ-lwHaK85qURrr24CZgOUzciq/view?usp=sharing

첨부된 동영상을 보시면 꽤 오랜시간이 지나도 웹뷰가 뜨지 않습니다.
꽤 오랜시간이 지난 후에 결국 밑 사진에 보이는것 처럼 로딩바가 돌았고, 결제 페이지에 진입할 수 있었습니다.

![iamport loading issue](https://user-images.githubusercontent.com/39753493/91126842-e7d7da80-e6df-11ea-8d8b-15f61cbe893c.jpeg)

와이파이와 LTE로 해도 별반 차이가 없는것으로 보아 인터넷 속도의 문제는 아닌것으로 보입니다.
pg사 : kcp.
flutter sdk : 1.17.0
device : lg x6
입니다.

확인부탁드립니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

로딩 컴포넌트("잠시만 기다려주세요")가 사라졌다는 것은 웹뷰 리소스(jquery, iamport javascript SDK) 로드가 완료됐다는 것을 의미하고
보고 계신 오른쪽 상단의 X버튼이 있는 빈 회색 창이 렌더링 됐다는 것은 KCP URL로 리디렉션이 완료됐다는 것을 의미합니다.
KCP URL로 리디렉션이 완료되면, KCP가 결제창 렌더링에 필요한 리소스(js, css 등)를 요청할텐데 이 과정이 오래 걸리는 것으로 아임포트와는 무관한 문제입니다.
정확히 어떤 이유 때문에 KCP 리소스를 불러오는데 오랜 시간이 걸리는지는 알 수 없으나
KCP SDK 문제, 특정 단말 문제, 인터넷 환경 문제 중 하나가 아닐까 생각됩니다.

와이파이와 LTE에서도 별반 차이가 없어 인터넷 문제는 아닌 것 같다고 하셨으니
다른 단말에서도 같은 이슈가 반복되는지 등을 확인해보시면 도움이 되시지 않을까 생각합니다.

또한 iamport_flutter가 내장하고 있는 [example 프로젝트](https://github.com/iamport/iamport_flutter/tree/master/example)를 같은 단말에 돌려보셨을때도 위와 같은 상황이 재현되시는지도 확인해보시면 좋을 것 같습니다. 저희가 갖고 있는 단말(갤럭시 S9)에서는 example 프로젝트로 KCP 결제창을 렌더링할때 같은 이슈가 재현되지 않기 때문에, 만약 재현되신다면 단말의 문제가 아닐까 싶습니다.

감사합니다.

**Comment by whatamelon** [comment]
답변감사합니다. 대표님께서 상세히 설명해주셨습니다^^ 감사합니다!
