### ISSUE TITLE
Nice 본인인증 지원 여부 문의

### ISSUE THREAD

**Issue by eunsang-oh** [iamport/iamport_flutter#124]
안녕하세요.
문의 할 수 있는 메뉴가 Issue 밖에 없어서 문의 드립니다.

NICE 본인인증을 도입 하려고 검토중인데 NICE측 문의 답변은 이용하려는 클라이언트 앱에 서버가 필수라고 합니다.

제 생각에 클라이언트 서버가 처리 할 부분이 없다고 생각해서 검색을 하다 iamport를 알게 되었구요
제 질문은
1> iamport를 이용하여  NICE평가정보의 본인인증을 클라이언트 서버 없이 구현 가능한지
2> 예제에는 다날,이니시스 관련 내용이  간략하게 나와 있는데 본인인증에 대한 구체적인 (NICE평가정보의 경우면 best) 예시가 따로 있는지
입니다.

두서 없는 글 확인 해 주셔서 감사합니다.

**Comment by anymate98** [comment]
안녕하세요.
우선 포트원에 나이스 본인인증이 현재 연동이 되어있지 않으므로 사용하실 수 없습니다.
플러터에 대한 내용은 아니지만 본인인증에 대한 내용과 좀 더 구체적인 예시는 [문서](https://developers.portone.io/docs/ko/etc/phone/readme?v=v1)를 참고하시면 될 듯 합니다.

포트원에서, 그리고 아마도 나이스도 비슷하겠지만 본인인증에 서버가 필요한 이유는 본인인증이 완료된 후 상세한 인증정보(이름, 생년월일, 휴대폰번호 등)을 받아오기 위해서는 별도의 api를 호출해야 하기 떄문입니다. 클라이언트에서 api 호출을 시도하신다면 CORS 에러를 확인하실 수 있을 것이고 이것이 본인인증에 서버가 필요한 이유입니다. 결제시에도 결제창은 클라이언트에서 띄우지만 api를 활용하기 위해서는 서버가 필요합니다.

**Comment by eunsang-oh** [comment]
상세한 답변 감사드립니다. 도움이 많이 되었습니다.
