### ISSUE TITLE
example/README.md 의 예제 실수가 있습니다.

### ISSUE THREAD

**Issue by benjioh5** [iamport/iamport_flutter#13]
https://github.com/iamport/iamport_flutter/blame/d8c1fd42600c99e60b1a9d2a9f9505f04c9c2e25/example/README.md

```
data: PaymentData.fromJson({
        'pg': 'html5_inicis',                                           // PG사
        'payMethod': 'card',                                           // 결제수단
        'name': '아임포트 결제데이터 분석',                                   // 주문명
        'merchantUid': 'mid_${DateTime.now().millisecondsSinceEpoch}', // 주문번호
        'amount': '39000',                                              // 결제금액
        'buyerName': '홍길동',                                           // 구매자 이름
        'buyerTel': '01012345678',                                     // 구매자 연락처
        'buyerEmail': 'example@naver.com',                             // 구매자 이메일
        'buyerAddr': '서울시 강남구 신사동 661-16',                         // 구매자 주소
        'buyerPostcode': '06018',                                      // 구매자 우편번호
        'appScheme': 'example',                                        // 앱 URL scheme
      }),
```
에서
```
'amount':'39000',
```
의 Value가 String일 경우 컴파일이 안 됩니다. 아마 API 스펙이 바뀌었거나, 문서 설명(Integer로 표기)와 다르게 예제가 나온 것 같습니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

네 말씀하신대로 예제 코드 해당 부분에 오류가 있는 것 같습니다. 이용에 혼란을 드려 대단히 죄송합니다.

[PaymentData](https://github.com/iamport/iamport_flutter/blob/master/lib/model/payment_data.dart#L14)모델이 정의된 부분을 보시면 `amount`의 데이터 타입은 **`integer`**입니다.
때문에 예제 프로젝트에서도 string으로 입력 받은 값을 [integer로 변환](https://github.com/iamport/iamport_flutter/blob/master/example/lib/screens/payment_test.dart#L239)하여 보내고 있습니다.
이용에 참고 부탁드립니다.

감사합니다.

**Comment by stevepark1004** [comment]
안녕하세요. flutter 로 아임포트 라이브러리를 통해 결제를 할려고 준비중에 있습니다. 해당 모듈을 실제 구동하기 위해 어떤것들을 준비해야 하는지요? 일단 샘플 예제를 구동시켜 아임포트 모듈을 실행시켜봤구요. 실행시켰더니 테스트용이라는 글자가 상단에  고정되어 있습니다. 해당 내용 변경 파라미터 값은 무엇인지 명세서 에는 안나와 있어서요. 이부분도 궁금하구요. 그리고 실제 저희 회사에서 해당 모듈을 사용할때 회원가입이나 혹은 어떤 모듈을 사용함에 있어 지불해야할 내용이 있나요? 그리고 하나더 저희 앱은 사용자가 카드 등록을 해놓으면 해당 정보로 간편 결제를 실행 하고 싶은데 해당 모듈로 구현이 가능할까요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

이곳은 다른 사용자께서 이슈를 남기신 곳이기 때문에, 여기에 답변하는 것은 적절하지 않은 것 같아
아임포트 기술지원팀(support@iamport.kr)으로 메일주소 남겨주시면, 답변드리도록 하겠습니다.

감사합니다.

**Comment by benjioh5** [comment]
확인하였습니다! 감사합니다!
