### ISSUE TITLE
본인인증 관련 이슈 문의드립니다.

### ISSUE THREAD

**Issue by JinPyoK** [iamport/iamport_flutter#138]
1. CertificationData의 pg 파라미터에 'danal'을 입력해도 KG 이니시스 본인인증 창이 열립니다.

2. KG 이니시스 통합인증 창이 열리고 바로 첫 화면에서 취소 버튼을 누르면, 다시 앱으로 돌아갈 것으로 기대하였으나 아무일도 벌어지지 않습니다. 앱바의 뒤로가기 화살표는 제대로 작동 합니다.

3. mRedirectUrl에 제 앱의 스킴 또는 딥링크를 넣으면 되는건가요? 어떠한 값을 넣어줘야 할지 잘 모르겠습니다 ㅠㅠ 본인인증이 완료된 이후 결과값 받고 그냥 제 앱으로 돌아가고 싶습니다.

환경은 안드로이드 에뮬레이터 안드로이드 13.0 티라미수, IOS 17.2 시뮬레이터, 제 핸드폰 안드로이드 10.0 Q 입니다.

**Comment by anymate98** [comment]
안녕하세요.

1. 관리자콘솔에 다날 본인인증 채널이 설정이 되어있지 않거나 대표 본인인증 채널이 아니라면 이니시스 본인인증이 뜨게 됩니다.
2. 이니시스 버그입니다. 7월 말에 수정 계획이라고는 전달받았습니다.
3. mRedirectUrl은 javascript sdk의 m_redirect_url과 같은 기능을 하며 결제 결과를 지정한 url(http)에 붙여서 결제완료 후 돌아가게끔 하는 파라미터입니다. iamport_flutter은 별개의 웹뷰를 띄워 결제를 실행 후 웹뷰 종료와 함께 콜백함수로 결제결과를 리턴하므로 사실 mRedirectUrl에 http(s)로 시작하는 url을 무엇을 넣어도 동일한 기능을 하게 되며 앱스킴이나 딥링크를 넣어 다른 앱으로 돌아가는 기능은 사용하실 수 없습니다.
