### ISSUE TITLE
결제 후, callback 함수에서의 result 값.

### ISSUE THREAD

**Issue by whatamelon** [iamport/iamport_flutter#14]
현재 callback에서는 {imp_uid: imp_247840466571, merchant_uid: 2-6348-1600060841713, imp_success: true}
이렇게 imp_uid, merchant_uid, imp_success 3개의 값만 리턴됩니다.

https://docs.iamport.kr/tech/imp#callback?lang=ko

가상계좌 입금시에 result에 해당 문서에 있는 모든 정보를 받고 싶은데 받을 수 있는 방법이 있을까요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

원래 KCP - 모바일 환경에서는 가상계좌 발급이 완료됐을때
`imp_uid`, `merchant_uid` 그리고 `imp_success`값만 전달됩니다.

이 `imp_uid`를 가지고 아임포트 REST API로 결제내역을 조회([GET /payments/{imp_uid}](https://api.iamport.kr/#!/payments/getPaymentByImpUid))해보시면 가상계좌 정보를 얻으실 수 있습니다.

이용에 참고 부탁드립니다.
감사합니다.

**Comment by whatamelon** [comment]
넵 확인했습니다. 감사합니다.
