### ISSUE TITLE
Flutter web 지원여부가 궁금합니다.

### ISSUE THREAD

**Issue by mgrv-yhlee** [iamport/iamport_flutter#145]
Flutter web 에서 아임포트가 동작하려면 javascript sdk 와 dart 를 연결하는 작업이 필요해 보입니다.

혹시 내부에서 진행중인 작업이 있을까요?
미래에 Flutter web 이 지원될 수 있는지 궁금합니다.

**Comment by CirnoV** [comment]
iamport_flutter는 모바일 SDK로, WebView에서 사용하는 것을 전제로 개발되었기 때문에 Flutter Web 에서는 작동하지 않습니다.

현재 이와 관련해 내부적으로 진행 중인 작업은 없으며, Flutter Web 환경에서 포트원 연동이 필요하다면 직접 JavaScript SDK를 통해 연동하셔야 합니다.
