### ISSUE TITLE
실시간 결제 오류

### ISSUE THREAD

**Issue by bongdong2** [iamport/iamport_flutter#15]
1. inappwebview를 통해 현재 모바일웹 페이지를 플러터 앱으로 런칭하려고 준비중입니다.
2. 아임포트PG 중개모듈을 사용하고요 나이스페이와 연결되어 실시간 계좌이체(뱅크페이) 앱을 통해 앱결제를 한 후 저희 앱으로 콜백은 되는데 PG창에서 리다이렉트가 되지 않고 있어요. 결제는 안되고 있고요 
혹시 관련하여 경험있으신 고수님들의 도움을 받을 수 있을 까요? 어디를 보면 좋을까요?

![IMG_4274](https://user-images.githubusercontent.com/24599350/97414379-40795d00-1947-11eb-8097-e1bf25055a11.PNG)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

inappwebview를 사용하신다는 말씀이, iamport_flutter 플러그인을 사용하고 계시지 않으시고
직접 웹뷰를 띄우셔서 IMP.request_pay 함수를 호출하고 계시다는 말씀일까요?

아마 이미 개발이 완료되신 웹 사이트를
flutter단에서 모두 웹뷰로 감싸서 재사용하기 위해서 그렇게 개발하고 계신 것 같은데
그렇다면 부득이하게 iamport_flutter 플러그인에서 내장하고 있는 필요한 로직을 모두 직접 작성해주셔야 합니다.

현재 연동하고 계신 나이스페이 - 실시간계좌이체는 특히나 별도의 코드를 작성해주셔야 하는데요,
iamport_flutter 플러그인의 소스를 기반으로 설명드리겠습니다.

```dart
/* NICE - 실시간 계좌이체 대비 : trigger incoming app link */
    _sub = getLinksStream().listen((String link) async {
      if (!mounted) return;
      try {
        PaymentData data = widget.data;
        if (link != null) {
          String decodedUrl = Uri.decodeComponent(link);
          Uri parsedUrl = Uri.parse(decodedUrl);
          String scheme = parsedUrl.scheme;
          if (scheme == data.appScheme.toLowerCase() &&
              data.pg == 'nice' &&
              data.payMethod == 'trans') {
            String queryToString = parsedUrl.query;

            /* [v0.9.6] niceMobileV2: true 대비 코드 작성 */
            String niceTransRedirectionUrl;
            parsedUrl.queryParameters.forEach((key, value) {
              if (key == 'callbackparam1') {
                niceTransRedirectionUrl = value;
              }
            });
            await webView.evalJavascript(''' 
              location.href = "$niceTransRedirectionUrl?$queryToString";
            ''');
          }
        }
      } on FormatException {}
    });
  }
```

뱅크페이 앱에서 계좌 인증 후, 귀하의 앱으로 돌아오게 되면 [getLinksStream().listen](https://github.com/iamport/iamport_flutter/blob/master/lib/iamport_payment.dart#L105)이  트리거됩니다.

이때 링크(URL)값이 null이 아닐 경우,
파싱해서 얻은 scheme값이 귀하의 앱 URL scheme값(IMP.request_pay시 전달한 app_scheme값)과 같은지 [체크](https://github.com/iamport/iamport_flutter/blob/master/lib/iamport_payment.dart#L113)를 하셔야 합니다.
이는 귀하의 앱이 열리게 된 계기가, 뱅크페이 앱에서 계좌 인증 후 열린 것인지를 판단하기 위함입니다.

링크 값을 파싱해서 얻은 쿼리 파라메터 중에서 callbackparam1값이, 귀하의 앱으로 돌아왔을때 리디렉션되어야할 URL입니다.
예를 들어 링크 값이 `app_scheme://?callbackparam1=https://www.naver.com&hello=world`라면
`https://www.naver.com`을 추출하고 나머지 쿼리 스트링을 뒤에 붙인 `https://www.naver.com?hello=world`로 [리디렉션](https://github.com/iamport/iamport_flutter/blob/master/lib/iamport_payment.dart#L126) 시켜주시면 됩니다.
이는 귀하의 앱으로 돌아왔을때 최종 결제 완료 버튼을 누른 효과를 가지게 됩니다.
현재는 위 로직이 작성되어있지 않기 때문에, 귀하의 앱으로 돌아왔을때 결제 완료 처리가 되지 않고 미결제 상태로 남아있는 것입니다.

이용에 참고 부탁드립니다.
감사합니다.
