### ISSUE TITLE
휴대폰 화면에 맞지 않게 보여지는 문제

### ISSUE THREAD

**Issue by turlvo** [iamport/iamport_flutter#16]
- iamport_flutter version: 0.9.9
- 핸드폰: 아이폰8
- iOS: 14.2
- 증상: 몇몇 유저에게 실명인증 화면이 화면에 핏하게 보여지지 않아
본인인증이 어려운 문제 발생

![IMG_1240](https://user-images.githubusercontent.com/24351423/101910729-b50c1080-3c02-11eb-92df-1ed3c0d43b75.PNG)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

아래와 같이 안내 주신 똑같은 환경에서
- 아이폰 8 실 기기(IOS 14.2)
- iamport_flutter v0.9.9

아임포트 본인인증 창을 호출 해보았을때 아래와 같이 정상적으로 렌더링 되는 것을 확인하였습니다.
![image](https://user-images.githubusercontent.com/42368261/102028076-a3399180-3deb-11eb-8f87-7f5ef318383a.png)

1. iamport_flutter 플러그인이 내장하고 있는 [example 앱](https://github.com/iamport/iamport_flutter/tree/master/example)을 해당 기기에서 실행해보셨을때도 같은 결과이실까요?
2. x축 y축으로 스크롤도 막혀있는 상황이실까요?
3. 혹시 사용자가 본인인증 창 진입 후 인위적으로 화면을 확대한 것은 아니실까요?

감사합니다.

**Comment by turlvo** [comment]
빠르고 자세한 확인 고맙습니다.

1. iamport_flutter 플러그인이 내장하고 있는 example 앱을 해당 기기에서 실행해보셨을때도 같은 결과이실까요?
네 에뮬 및 동일 기종으로 확인 해보았지만 자체 재현은 안되었습니다.
그런데 몇몇 고객에게 동일한 증상이 발생했다는 문의가 들어오고 있는 상태입니다.

2. x축 y축으로 스크롤도 막혀있는 상황이실까요?
네, 화면 이동이 안되는지 본인인증이 불가하다고 리포트 받고 있습니다.

3. 혹시 사용자가 본인인증 창 진입 후 인위적으로 화면을 확대한 것은 아니실까요?
인위적인 확대는 아닌 것 같습니다. 
확대 기능도 없고, 한 고객이 아니고 동일한 증상 화면 3,4건 리포트 되었습니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

답변 감사드립니다.
제가 example 앱으로 확인해보았을때 본인인증 창 진입 후 인위적으로 확대해보면
첨부 주신 화면과 같은 화면이 렌더링 되었기 때문에 혹시 사용자가 확대를 했던 것인지 확인차 문의 드렸습니다.
물론 그렇게 인위적으로 확대한다고 하더라도 스크롤이 생기기 때문에 화면 내 이동이 가능하여 다음 단계로 진행이 가능한 상태인데,

이슈 보고를 해주신 유저분이 지속적으로 해당 현상을 겪고 계신건지
아니면 가끔 또는 일시적으로 해당 현상을 겪으신 것인지 궁금합니다.

저희로서는 원인 파악이 우선 되어야 해결을 할텐데, 재현이 되지 않아 원인 파악이 힘들어
진전이 없는 상태입니다. 양해 부탁드립니다.

감사합니다.

**Comment by turlvo** [comment]
네, 알겠습니다.

다른 유저 iphone se에서 발생한 모습입니다.

![IMG_4454](https://user-images.githubusercontent.com/24351423/102173140-b9277f00-3edd-11eb-92fa-1ef7d10236a3.PNG)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

앞서 안내드린 바와 같이 이슈 보고를 해주신 유저분이 지속적으로 해당 현상을 겪고 계신건지
아니면 가끔 또는 일시적으로 해당 현상을 겪으신 것인지 확인 되시면 안내 부탁드립니다.

감사합니다.

**Comment by turlvo** [comment]
안녕하세요.

지속적으로 몇몇 아이폰 유저에게 리포트 받고 있는 상태입니다.
발생한 유저는 계속 발생해서 본인인증이 어려운 상태라, 살펴보고 있습니다.

확대/축소, 스크롤이 불가능해서 진행이 안된다고 고객센터로 문의가 들어오네요.

**Comment by turlvo** [comment]
userAgent 문제로 의심되어 로컬패키지로 가져와서 아래와 같이 수정하여 사용중입니다.

'iamport_webview.dart' WebviewScaffold Widget의 userAgent 파라미터에
모바일 agent 값을 넣어서 해결 하였습니다.

```
'Mozilla/5.0 (Linux; U; Android 4.0.3; de-ch; HTC Sensation Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30';
```

**Comment by anymate98** [comment]
안녕하세요, 아임포트 기술지원팀입니다.

현재 새로운 본인인증 ui를 사용하고 계실텐데 만약 pc버전의 모습으로 보이는 증세가 보인다면 viewport를 바꿔주시면 됩니다.
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
