### ISSUE TITLE
Flutter 에서 정기결제 모듈도 존재하나요?

### ISSUE THREAD

**Issue by ijunc2** [iamport/iamport_flutter#21]

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

정기결제를 위해서는 우선, 정기결제 수단(신용카드 또는 휴대폰 소액결제를 위한 휴대폰 정보)을 등록해야하는데
이때 크게 2가지 방법이 가능합니다.

1. 일반결제와 같이 PG사 결제창을 통한 등록
2. 아임포트 REST API를 통한 등록

현재 iamport_flutter 플러그인은 1번을 통한 정기결제 수단 등록만 지원하고 있으며
2번은 REST API 호출을 통해 가능하므로 iamport_flutter 플러그인과 무관하게 직접 연동하셔야 합니다.
즉, 2번을 통해서 연동을 하실 예정이시라면, iamport_flutter 플러그인을 연동하실 필요는 없으십니다.

- [아임포트 REST API](https://api.iamport.kr/)
- [아임포트 정기결제 연동하기](https://docs.iamport.kr/implementation/subscription)

이용에 참고 부탁드립니다.
감사합니다.
