### ISSUE TITLE
Flutter Web 에서 동작은 어떻게 처리되나요?

### ISSUE THREAD

**Issue by wooyah-jeong-allstay** [iamport/iamport_flutter#22]
macOS Catalina 입니다
Flutter 로 웹앱을 만들고 있고, 아임포트 예제를 따라서 해봤더니
Unsupported operation: Platform._operatingSystem 오류가 나오네요

웹은 설정을 어떻게 처리해줘야 하나요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

iamport_flutter 모듈은 안드로이드/IOS만 지원하고 웹에서의 결제는 지원하지 않습니다.

아임포트를 이용한 결제창 호출은 기본적으로 자바스크립트 함수 호출만 해주시면 되는데
앱에서는 결제를 위해 귀하의 앱 <-> 외부 앱(카드사 앱, 간편결제 앱)간 이동을 위한 추가 로직이 필요하여
iamport_flutter와 같은 모듈을 제공하고 있습니다.

웹에서의 결제는 [아임포트 일반결제 연동하기](https://docs.iamport.kr/implementation/payment) 문서를 참고하셔서
자바스크립트 함수를 호출하는 방식으로 연동해주시면 됩니다.

감사합니다.
