### ISSUE TITLE
Flutter 2 버전 지원

### ISSUE THREAD

**Issue by leejh10003** [iamport/iamport_flutter#25]
현재 Flutter 2 버전으로 저희 서비스의 Migration을 준비중인데, Flutter 2 버전이 제대로 지원되지 않고 있습니다.
죄송하지만, Flutter 2 버전에 대한 지원은 언제쯤 추가될 예정인가요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

현재 iamport_flutter V2 마이그레이션 작업이 진행되고 있으며
iamport_flutter가 dependent한 flutter_webview_plugin이 V2를 지원하지 않는 관계로
다른 플러그인으로 대체하느라 시간이 다소 소요되고 있는데, 마무리까지 약 2주 정도 소요될 것으로 생각됩니다.

이용에 불편을 드려 대단히 죄송합니다.
감사합니다.

**Comment by leejh10003** [comment]
감사합니다. 혹시나 하는 마음에 [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) 확인을 추천드립니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

저희도 flutter_inappwebview 패키지와 webview_flutter 패키지 두 개를 모두 테스트 해보고 있었습니다.
추천 감사드립니다 👍

**Comment by jungsangeun** [comment]
> 안녕하세요 아임포트 기술지원팀입니다.
> 
> 저희도 flutter_inappwebview 패키지와 webview_flutter 패키지 두 개를 모두 테스트 해보고 있었습니다.
> 추천 감사드립니다 👍

https://pub.dev/packages/iamport_flutter의 최신 버전이 업데이트가 되어 있지 않는 것 같은데요.
(pub install을 하려고 0.10.0 버전을 찾을 수가 없다고 합니다ㅜ)
혹시 배포 일정을 알 수 있을까요?
