### ISSUE TITLE
본인인증 진행중 zoom 이 땡겨지는 문제

### ISSUE THREAD

**Issue by onesup** [iamport/iamport_flutter#3]
iOS 에서 `showDialog` 를 사용하여 `IamportCertification` 을 실행하면,
본인인증을 진행하다 아래 화면에서 자동으로 zoom 이 들어갑니다.

![image](https://user-images.githubusercontent.com/298348/69859513-a395e600-12d7-11ea-925e-1867d00d54e3.png)

혹시 이 라이브러리에서 쓰고 있는 WebviewScaffold 옵션을 바꿔보면 어떨까 싶어서
```
rect: false,
withZoom: true,
```
같은 옵션을 줘도 마찬가지입니다.

어떻게 해결하면 좋을까요?

일단 `showDialog` 말고 새로 page 로 빼서 작업해보려고 합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

아임포트 플러터 모듈 사용시 페이지로 빼서 작업하길 권장하고 있어
안내 메뉴얼도 같은 방식으로 작성했습니다만,
보고해주신 부분 확인 후 안내도와드리겠습니다.

혹시 페이지로 빼서 다시 작업하셨을때는 문제가 해결되겼을까요?

감사합니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

확인 결과, 해당 사항은 캡쳐해주신 화면에서 `휴대폰본인확인(문자)` 탭을 눌렀을때
이름입력 부분이 포커스 되면서 줌 인 되는 자연스러운 현상입니다.
원하신다면 본인인증 웹뷰를 띄우는 html 파일의 meta 태그에 user-scalable 속성을 no로 설정하면
포커스 되더라도 줌 인이 되지 않도록 할 수 있습니다만,
웹뷰 소스 자체가 string으로 되어있어 유저에게 boolean 값으로 prop을 받아 적용하기엔 어려움이 있습니다.
많은 유저가 보편적으로 원하는 값이라면 전체적으로 반영을 하겠으나
현재 귀하 외엔 같은 이슈나 요구사항이 있어 조심스러운 부분입니다.

정말 필요하시다면 저희 모듈을 fork 뜨신 후,
lib/iamport_webview.dart 파일의 html 값을 아래와 같이 수정해 사용하시면 됩니다.

```
static final String html = '''
    <html>
      <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
       <!-- user-scalable을 no로 설정 -->
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0">

        <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js" ></script>
        <script type="text/javascript" src="https://cdn.iamport.kr/js/iamport.payment-1.1.7.js"></script>
      </head>
      <body></body>
    </html>
  ''';
```

감사합니다.

**Comment by onesup** [comment]
빠른 답변 주셔서 감사합니다!

**Comment by SoleeChoi** [comment]
감사합니다 :)
