### ISSUE TITLE
0.10.0-dev.1 ios build 오류 

### ISSUE THREAD

**Issue by pavecho** [iamport/iamport_flutter#33]
안녕하세요. 
이번에 null safety migration을 진행했는데 안드로이드는 잘 되지만 ios 빌드 시 아래와 같은 오류가 발생합니다.

> objc[1882]: Class FLTJavaScriptChannel is implemented in both /private/var/containers/Bundle/Application/E6F9894E-56FA-42D4-84B2-4D257702B8B0/Runner.app/Frameworks/webview_flutter.framework/webview_flutter (0x101b6bc58) and /private/var/containers/Bundle/Application/E6F9894E-56FA-42D4-84B2-4D257702B8B0/Runner.app/Frameworks/iamport_webview_flutter.framework/iamport_webview_flutter (0x101a6fd78). One of the two will be used. Which one is undefined.
2021-07-01 11:49:58.175853+0900 Runner[1882:1375678] Metal API Validation Enabled
2021-07-01 11:49:58.383380+0900 Runner[1882:1375894] 8.0.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
2021-07-01 11:49:58.444412+0900 Runner[1882:1375678] [Firebase/Crashlytics] Version 8.0.0
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: FLTWebViewFlutterPlugin'
terminating with uncaught exception of type NSException
2021-07-01 11:49:58.509477+0900 Runner[1882:1375678] *** Assertion failure in -[FlutterEngine registrarForPlugin:], FlutterEngine.mm:865
2021-07-01 11:49:58.512775+0900 Runner[1882:1375678] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: FLTWebViewFlutterPlugin'
*** First throw call stack:
(0x220edf180 0x2200b79f8 0x220df888c 0x2218bcb38 0x101b93c08 0x100fc8748 0x100fc8814 0x100fc8b1c 0x24d6c40f0 0x24d6c5854 0x24d6cafe0 0x24cf8e2a4 0x24cf9683c 0x24cf8df28 0x24cf8e818 0x24cf8cb64 0x24cf8c82c 0x24cf9136c 0x24cf92150 0x24cf91224 0x24cf95f24 0x24d6c95e8 0x24d2c5e04 0x22385b9fc 0x22386540c 0x223864c14 0x103c08c78 0x103c0c840 0x223896040 0x223895cdc 0x223896294 0x220e70f1c 0x220e70e9c 0x220e70784 0x220e6b6c0 0x220e6afb4 0x22306c79c 0x24d6ccc38 0x100fc8ce0 0x22092e8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

플러그인 버전
```
webview_flutter: ^2.0.9
iamport_flutter: ^0.10.0-dev.1
dart_json_mapper: ^2.1.1
```
Flutter version 2.0.3
Dart version 2.12.2

**Comment by anymate98** [comment]
안녕하세요, 아임포트 기술지원팀입니다.
이러한 문제가 발생하는 이유는 webview_flutter 자체의 기능 부족으로 인해 저걸 포크해서 임시적으로 웹뷰 플러그인을 만들어 사용하고 있기 때문입니다. 원래 그렇게 할 이유가 전혀 없었지만 서드파티 쿠키 허용 같은 기능들이 공식 플러그인에 빠져 있어 저희가 제공하는 플러그인에서는iamport_webview_flutter을 만들어 사용중에 있습니다.
flutter_inappwebview 같은 경우에는 필요한 기능들이 잘 구현되어 있지만 url 파싱에 해결 불가능한 문제가 있어 사용하지 못했습니다.
임시적으로 사용중이신 웹뷰 플러그인을 iamport_webview_flutter로 교체해 사용하시면 본문의 문제가 해결될 것 같고 현재 오류에 대해 해결방안을 모색하고 있습니다.

**Comment by pavecho** [comment]
답변 감사합니다! 플러그인 교체해서 해결했습니다.

근데 다른 이슈인데.. 업그레이드 후 initialChild 가 지금 보이지 않습니다. 
흰 화면만 나옵니다.

**Comment by anymate98** [comment]
initialChild는 로딩중에 임의의 화면이 표시되도록 만들어놓은 파라미터인데 혹시 흰 화면 등장 이후 결제는 정상적으로 되시나요?
안드로이드 ios 두 플래폼 중 어느곳에서 일어나는 문제인지도 확인이 필요할 것 같습니다.

**Comment by pavecho** [comment]
안드로이드 ios 두 플랫폼 다 initialChild가 나오지 않고 흰 화면이 나옵니다.
그 후 본인인증 프로세스는 정상적으로 동작합니다.

**Comment by anymate98** [comment]
혹시 initialChild에 아무것도 안넣고 실행해도 그런가요? 파라미터가 비어있다면 미리 설정된 로딩 화면을 보여주게 되어있습니다.
그것과 별개로 저도 테스트해보고 결과를 공유해드리겠습니다.

**Comment by pavecho** [comment]
네. 똑같습니다.

**Comment by anymate98** [comment]
점검을 좀 해본 결과 이 현상은 정상적인 것으로 확인됩니다.
웹뷰가 로딩이 빠르게 되지 않을 경우를 대비한 것이기 때문에 실제 기기의 속도가 유의미하게 느린 것이 아니라면 initialChild는 아예 표시가 안될 것 같고요 흰 화면은 웹뷰상에서 다날 본인인증 창 자체가 렌더링중이기 때문에 나오는 것으로 보입니다.
