### ISSUE TITLE
PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript.. 오류 문의

### ISSUE THREAD

**Issue by jungsangeun** [iamport/iamport_flutter#39]
0.10.0-dev.4 버전을 사용하고 있습니다.
실제 결제도 정상적으로 이루어지고 result callback 도 정상적으로 들어오고 있는데
결제 할 때마다 PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: '...
로그가 출력되고 있습니다.
확인 부탁드립니다.

**Comment by anymate98** [comment]
네 예전부터 있던 문제인데 무분별하게 자바스크립트를 실행해 발생했던 것 같습니다.
이후 버전부터는 해당 로그 보이지 않도록 조치하겠습니다.
