### ISSUE TITLE
라이센스 관련 질문 및 flutter로 인테그레이션 시, 안드로이드 빌드 에러 문의드립니다.

### ISSUE THREAD

**Issue by Edward-Kwak** [iamport/iamport_flutter#40]
안녕하세요,
아임포트 소스코드 사용에 대한 라이센스 질문과
안드로이드 빌드 시 빌드에러에 관하여 문의드립니다.

1. 안드로이드 빌드 시 빌드 에러 관련 문의.
    
    pubspec.yaml 의 디펜던시에
    iamport_flutter: ^0.10.0-dev.4 을 추가해주고,
    
    build.yaml 파일도 생성한 후,
    flutter pub run build_runner build --delete-conflicting-outputs 
    dart run build_runner build
    위 두 명령어를 차례로 입력하여 빌드하고,
    안드로이드 스튜디오 에뮬레이터로 실행해보면 정상적으로 본인인증 뷰가 나옵니다.
    
    그런데, 개발에 사용된 모든 패키지들과 환경을, 다른 서버에서 똑같이 구현하고,
    release 파일을 빌드하기위해
    
    flutter build apk 명령어를 입력하니 아래와 같은 에러가 발생합니다.
    (에러 메시지 상단 부분만 캡쳐했습니다.)
    
    ![image](https://user-images.githubusercontent.com/42112227/133580319-9d99f394-2d95-4d8e-b3bc-d9d573e527e7.png)
    
    (아임포트를 적용하기 전에는 다른 여러 패키지들을 사용하고, 해당 서버에서 환경을 똑같이 하여
    flutter build apk 명령어를 입력하면 정상적으로 빌드가 잘 되곤 했습니다.)
    
    아임포트 패키지를 추가한 뒤에는 위와 같이 파일을 찾지 못하는 빌드 에러가 발생합니다.
    
    pubspec.yaml 에 추가한 iamport_flutter 패키지를,
    아래와 같은 형태로도 다운로드 하여 시도해보았으나 여전히 같은 에러가 발생했습니다.

    iamport_flutter:
    >git:
      >>url: https://github.com/iamport/iamport_flutter.git
  
    하여, iamport_flutter 패키지를 flutter 프로젝트에 적용 후,
    안드로이드 부분에서 빌드 시 에러가 발생하는 듯 하여 인테그레이션 관련하여 문의드립니다.
    
    "flutter 프로젝트 폴더/android/app/src/main/AndroidManifest.xml" 파일이나
    "flutter 프로젝트 폴더/android/app/build.gradle" 파일에 무언가를 별도로 추가해야 하는 것인지,
    
    아니면 다른 방법으로 해결할 수 있는지 질문드립니다..

2. 아임포트 소스코드 사용에 대한 라이센스 문의

    위 1번과 같은 문제를 해결하고자
    
    저는 임시적으로 "flutter 프로젝트 폴더/lib/" 경로에
    이 git에 있는 소스코드 "lib" 폴더 내에 있는 모든 코드를 붙여넣었고,
    
    iamport_flutter 패키지에서 사용하는 다른 패키지들을 전부 pubspec.yaml 에 등록함으로써
    
    위 빌드 에러를 일시적으로 해결하긴 했습니다.
    
    하지만 이와 같은 방법은
    이후 업데이트 되는 버전 관리와
    라이센스 문제가 생길 것으로 우려되어 문의드립니다.
    
    업데이트 되는 버전 관리는, 
    제가 직접 수동적으로 매번 업데이트 때마다 이 git에서 가져와서 코드를 적용한다고 하더라도,
    
    제가 개발중인 이 프로젝트가 상용화 되었을 경우에
    라이센스 문제가 가장 우려되는데,
    flutter 프로젝트 폴더 안에, 이 git 에서 다운받은 소스코드를 직접 넣어서 상용화 하여도 괜찮은지 문의드립니다.

긴 글 읽어주셔서 감사합니다.

**Comment by anymate98** [comment]
문의주셔서 감사합니다.

이미 코드를 받아서 앱에 필요한 방식으로 변경해 서비스하시는 분들이 계시므로 라이센스에 관한 부분은 염려하지 않으셔도 됩니다.
다만 추후 업데이트 및 사용시 생기는 문제를 해결하기 위해 문의를 주실 때 번거로움이 생길 수 있습니다.

이와 별개로 위에서 언급하신 문제는 아마 캐시 문제가 아닐까 합니다.
gradle 및 flutter프로젝트의 캐시를 깔끔하게 비운 후 다시 시도해보셨는지 궁금합니다.

**Comment by Edward-Kwak** [comment]
빠른 답변 감사합니다.

네 캐시 문제일까도 싶어서, flutter pub cache repair 명령 및 flutter clean, rm -rf ~/.pub-cache 등의 명령어를 입력한 후,

다시 빌드하여 안드로이드 시뮬레이터 상에서 정상동작을 확인한 후
서버에 환경을 동일하게 하여 올린 뒤, flutter build apk 를 하였으나

여전히 같은 빌드 에러 메시지를 접하였습니다.

**Comment by anymate98** [comment]
저도 지금까지 명령어로 apk만 빌드해본적이 없었는데 로컬에서 해보니 안됩니다. 조금 더 해결방법을 알아본 후 다시 답변 드리겠습니다.

**Comment by Edward-Kwak** [comment]
네 답변 감사합니다.

그래도 라이센스 문제는 염려하지 않아도 된다니 다행입니다.
일단 당장에는 아임포트 소스코드를, 개발중인 flutter 프로젝트 폴더내에 포함시켜 개발하는 방식으로 진행하겠습니다.

빠르고 명쾌한 답변 감사합니다. :)

**Comment by anymate98** [comment]
flutter 2.5.0에서는 빌드 실패했는데 2.5.1로 업데이트 후 다시 apk 빌드를 시도했더니 성공했습니다.
아직 apk 빌드를 못하셨다면 버전을 올려서 해보시겠어요?

**Comment by Edward-Kwak** [comment]
감사합니다.
flutter 버전을 2.5.0 을 이용중이었는데 말씀대로, flutter 버전 업데이트 이후 빌드에 성공하였습니다. :)
