### ISSUE TITLE
Tablet Size

### ISSUE THREAD

**Issue by JeongEEE** [iamport/iamport_flutter#42]
안녕하세요

아임포트 본인인증 서비스를 태블릿 가로화면에서 사용하려고 합니다

![Screenshot_20211006-144227](https://user-images.githubusercontent.com/51220239/136147033-c93901ec-154d-41c8-b69d-0b56e6de3246.png)

해당화면이 너무 크게 보이는데 축소가 가능한지요?

**Comment by anymate98** [comment]
![IMG_E4DE9E6795C6-1](https://user-images.githubusercontent.com/26593166/136178528-48ddef9a-5ca9-49fa-8ff0-e6b19436a3f0.jpeg)

제 아이패드에서 예제를 실행해본 화면입니다. 
```
return IamportCertification(
      appBar: new AppBar(
        title: new Text('아임포트 본인인증'),
        centerTitle: true,
        leading: IconButton(
          icon: Icon(Icons.arrow_back_ios),
          onPressed: () {
            Get.back();
          },
        ),
      ),
      initialChild: SafeArea(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Image.asset('assets/images/iamport-logo.png'),
              Padding(padding: EdgeInsets.symmetric(vertical: 15)),
              Text('잠시만 기다려주세요...', style: TextStyle(fontSize: 20.0)),
            ],
          ),
        ),
      ),
      userCode: userCode,
      data: data,
      callback: (Map<String, String> result) {
        Get.offNamed('/certification-result', arguments: result);
      },
    );
```
제가 실행한 코드는 이렇고요, 혹시 구동하신 환경 및 상응하는 코드를 공유해주실 수 있을까요?

**Comment by JeongEEE** [comment]
iamport_flutter: ^0.10.0-dev.4 버전이구요
android-arm64 태블릿 디바이스 입니다

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

initialChild 안에 위젯이 Container로 고정되어 있는데 원인이 이것때문일까요?
SafeArea로 변경이 안되네요
![스크린샷 2021-10-07 오전 10 32 20](https://user-images.githubusercontent.com/51220239/136306258-43c56d39-8f21-47de-9ae2-3c560fe29f3e.png)



```
  @override
  Widget build(BuildContext context) {
    return IamportCertification(
      appBar: new AppBar(
        title: new Text('본인인증'),
      ),
      /* 웹뷰 로딩 컴포넌트 */
      initialChild: Container(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CupertinoActivityIndicator(radius: 35,),
              Container(
                padding: EdgeInsets.fromLTRB(0.0, 30.0, 0.0, 0.0),
                child: Text('잠시만 기다려주세요...', style: TextStyle(fontSize: 20.0)),
              ),
            ],
          ),
        ),
      ),
      /* [필수입력] 가맹점 식별코드 */
      userCode: userCode,
      /* [필수입력] 본인인증 데이터 */
      data: userData,
      /* [필수입력] 콜백 함수 */
      callback: (Map<String, String> result) {
        print('### Result- ' + result.toString());
      },
    );
  }
```

**Comment by JeongEEE** [comment]
SafeArea의 유무는 해결방법이 아닌것 같습니다

IamportCertification를 Container로 감싸서 width설정을 해줘도 화면에 꽉차는데 혹시
별도의 설정 방법이 있는지요?

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.
해당 페이지는 다날에서 띄우는 페이지이기에 저희가 컨트롤 할 수 없는 영역입니다.

아이패드에서 작게 보이는 이유는 iOS13 부터 아이패드 설정에 의해 PC 로 간주하여, pc 버전의 팝업 UI 가 띄워졌기 때문입니다.
임의로 UserAgent 를 조작하여 pc 환경의 UI 를 띄울 수는 있겠으나, 
저희가 권장 드리는 방식은 아니며 정상동작을 보장하기는 어렵습니다.
감사합니다.
