### ISSUE TITLE
net::ERR_UNKNOWN_URL_SCHEME 에러 문의드립니다.

### ISSUE THREAD

**Issue by Edward-Kwak** [iamport/iamport_flutter#48]
안녕하세요,
이전에 답변주신대로 잘 적용하여 사용하던 중, 갑자기 이번에 새로운 이슈가 발생하여 문의드리게 되었습니다.
(현재 사용중인 버전은 iamport_flutter: ^0.10.0-dev.4, iamport_webview_flutter: ^3.0.3 입니다.)

우선 화면을 보여드리자면, 아래와 같습니다.

우선, 본인인증 최초 화면 UI가 업데이트 되어있었습니다.

<img src="https://user-images.githubusercontent.com/42112227/139364403-6a3cf752-f0ed-44e4-9877-866d94c6ecdd.png" width="30%" height="30%" />

그후, 본인인증 을 위해 통신사와 동의 부분을 클릭 후, PASS로 인증하기 를 누르면,
PASS 앱이 실행되기 전에 아래와 같은 URL_SCHEME 에러가 나오고,
PASS 앱에서 정상적으로 인증을 완료하고 다시 앱으로 돌아온 뒤에도,
아래 화면이 그대로 남아 유지되어 있습니다.
(해당 화면은 리다이렉션 화면인 것으로 추정됩니다.)

<img src="https://user-images.githubusercontent.com/42112227/139364635-0a1b4a0c-06a1-4dc2-b547-7f7786d7d4b3.png" width="30%" height="30%" />

추측되는 바로는,
intent 라는 형식의 URL을 지원하지 않아서 생기는 문제인 것 같습니다.

업데이트 되기 전에는 https 였던 것으로 추측하고 있는데,
업데이트 후 intent 로 바뀌었기 때문인 것으로 생각됩니다.

IOS 에서는 URL SCHEME 에러 없이 아래와 같이 정상적으로 작동합니다.

<img src="https://user-images.githubusercontent.com/42112227/139381906-1d215f55-bb5c-4837-83d1-b1940ed64cc7.png" width="30%" height="30%" />

<img src="https://user-images.githubusercontent.com/42112227/139381931-d33c40c6-4424-4d81-ab09-a3561974d80f.png" width="30%" height="30%" />

<img src="https://user-images.githubusercontent.com/42112227/139381940-e00e8fbd-c7ef-4f84-a83e-961e6a7597e2.png" width="30%" height="30%" />

차이점은, IOS에서는 pass 앱이 자동으로 실행되면서 인증과정을 거치는 게 아니라는 점 인듯 합니다.

안드로이드에서 intent URL Scheme에 대해 처리하는 과정에서 문제가 있는 것으로 보입니다.

혹시나 싶어,
프로젝트 폴더 내의, android > app > src > main > AndroidManifest.xml 에서,

```
<intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="intent"/>
</intent-filter>
```

위와 같이 수정하여 해보았으나, 이또한 실패하였습니다.

플러터 버전을 master 채널에서, 최신으로 업데이트 하였으나 이 또한 실패하였습니다.
(현재 플러터 버전은 2.6.0-12.0.pre.519 입니다.)

혹시 이 문제를 해결할 방법이 없을까 하여 문의드립니다.

감사합니다.

**Comment by anymate98** [comment]
안녕하세요, 아임포트 기술지원팀입니다.

최근에 다날 본인인증 ui가 바뀐 것을 확인하였습니다.
다만 아임포트 가맹점들의 경우 몇번에 걸쳐 순차적으로 바뀌게 되었다는 사실을 확인했고 재현하는데 시간이 오래 걸린 점 양해 부탁드립니다.

웹뷰의 경우 m_redirect_url을 명시해주시면 해당 에러 페이지를 보는 것을 방지할 수 있었습니다.
다만 현재 버전에는 해당 파라미터가 빠져 있어 직접 소스를 수정해서 사용하시는 것이 아니라면 당장 해결이 힘들 것 같습니다.
되도록 빠른 시일 내에 패치를 포함한 버전을 배포하도록 하겠습니다.

**Comment by anymate98** [comment]
해당 문제 해결한 버전 v0.10.0-dev.5 배포했습니다.
m_redirect_url 명시해서 사용해주시면 감사하겠습니다.

**Comment by Edward-Kwak** [comment]
안녕하세요, 회사 내 다른 문제로 여지껏 이슈에 대한 테스트를 진행하지 못하다가, 이제서야 진행하고 이슈가 해결된 것을 확인하였습니다.

그런데 질문이 있습니다.

안내해주신 대로,  v0.10.0-dev.6 버전으로 업그레이드를 진행하였고,
업그레이드 후 본인인증 관련 함수인 CertificationData 에 새로운 mRedirectUrl 파라미터가 추가된 것도 확인되었습니다만,

mRedirectUrl 값을 rest api 문서에 있는 "SMS본인인증결과 조회 및 관리" 의
API방식으로 휴대폰 본인인증 프로세스를 시작하는  https 형태 url을 넣어주면,
`{"code":-1, "message": "Unauthorized", "response": null}`
이 적혀있는 에러화면이 IOS, Android 둘다 동일하게 나옵니다.

그러나 신기하게도 mRedirectUrl : "" 형태로 하고 진행하면, IOS 랑 Android 상에서 아무 문제없이 본인인증이 정상적으로 진행 되었습니다.

혹시 어떤 형태로 mRedirectUrl 값을 명시해야 하는지 알 수 있을까요?

아니면 그냥 이대로 mRedirectUrl 값을 "" 형태로 주고 사용해도 큰 문제가 없는 것인지 궁금합니다.

감사합니다.

**Comment by anymate98** [comment]
결론적으로 말하자면 m_redirect_url은 명시하지 않으셔도 됩니다.
이번에 다날 본인인증과 일반결제에서 문제가 발견되었는데 둘 다 웹뷰가 iframe 안의 url 변화를 컨트롤하지 못해 일어날 일입니다.
dev.5 이후 웹뷰에 기능이 없었다는 것이 진짜 원인임을 깨닫고 해당 사항 조치한 것이 dev.6 버전이고 본인인증의 문제 또한 동시에 해결되었습니다.
m_redirect_url을 명시했을 경우 작동한 이유는 해당 파라미터를 명시할 경우 iframe이 아닌 redirect 모드로 작동하기 때문에 url 변화를 감지할 수 있기 때문입니다. 현재는 두 모두 정상 작동할 것입니다.

**Comment by Edward-Kwak** [comment]
아하 그랬군요!

빠른 업데이트와 명쾌한 답변 감사드립니다.

이슈는 닫도록 하겠습니다. 감사합니다. :)
