### ISSUE TITLE
0.10.0-dev.4 빌드시 dart_json_mapper 이슈

### ISSUE THREAD

**Issue by dyt9120** [iamport/iamport_flutter#49]
README 안내를 따라서 main() 함수에 initializeJsonMapper();를 호출하였습니다.
모든 세팅을 마친 후 빌드를 하면 아래와 같은 에러가 발생합니다:

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Bad state: Reflectable has not been initialized.
Please make sure that the first action taken by your program
in `main` is to call `initializeReflectable()`.

아임포트 깃헙 예제에서는 initializeReflectable()이 없던데 어떻게 우회할 수 있나요?

main() 함수는 아래와 같습니다(Future가 아닌 void main()에서 initializeJsonMapper()을 시도해도 마찬가지입니다.)
Future<void> main() async {
  await initializeJsonMapperAsync();
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

**Comment by anymate98** [comment]
안녕하세요, 아임포트 기술지원팀입니다.

https://github.com/iamport/iamport_flutter/issues/36

mapper의 생성은 생성하고자 하는 코드의 존재가 필요합니다.
main 함수에서 직간접적으로 iamport_flutter의 코드에 접근할 수 있도록 코드가 구성되어야 하겠습니다.

**Comment by dyt9120** [comment]
[해결방법]
main.dart에 iamport_flutter 코드를 사용하는 파일을 import 해놓으면 됌
