### ISSUE TITLE
농협카드 - 앱카드 Scheme명 오류..?

### ISSUE THREAD

**Issue by iOS-Kiwon** [iamport/iamport_flutter#5]
<string>nhappvardansimclick</string> 

해당 scheme이 맞는지 확인부탁드려요~

card를 의미하는 'C'가 맞을듯합니다.
  <string>nhappcardansimclick</string>

**Comment by jangbora** [comment]
내부적으로 처리하는 과정에서 실수가 있어 오타가 들어갔습니다. 양해부탁드립니다. 
말씀주신 것처럼 nhappcardansimclick 가 맞는 것으로 확인되어, github에 수정하였습니다. (아직 flutter 패키지 버전업은 하지 않았습니다)

농협 올원페이(nhallonepayansimclick)로 NH앱카드 앱들이 모두 통합된 것 같은데, 혹시 해당 앱 호출에 실패하는 경우가 있으셨을까요?

제보해주셔서 감사드립니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 내용은 다른 커밋과 함께 v0.9.9에 반영되었습니다.

감사합니다.
