### ISSUE TITLE
Android 12 본인인증 키보드 오류

### ISSUE THREAD

**Issue by pavecho** [iamport/iamport_flutter#53]
Android 12에서 본인인증 시 키보드가 뜨지 않고 아래 에러가 발생합니다.
애뮬레이터에서도 입력이 안됩니다.

> V/InputMethodManager( 4621): b/117267690: Display ID mismatch found. ViewRootImpl displayId=2 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
V/InputMethodManager( 4621): java.lang.Throwable
V/InputMethodManager( 4621): 	at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:549)
V/InputMethodManager( 4621): 	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1843)
V/InputMethodManager( 4621): 	at org.chromium.content.browser.input.ImeAdapterImpl.H(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:4)
V/InputMethodManager( 4621): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:30)
V/InputMethodManager( 4621): 	at android.os.MessageQueue.nativePollOnce(Native Method)
V/InputMethodManager( 4621): 	at android.os.MessageQueue.next(MessageQueue.java:335)
V/InputMethodManager( 4621): 	at android.os.Looper.loopOnce(Looper.java:161)
V/InputMethodManager( 4621): 	at android.os.Looper.loop(Looper.java:288)
V/InputMethodManager( 4621): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
V/InputMethodManager( 4621): 	at java.lang.reflect.Method.invoke(Native Method)
V/InputMethodManager( 4621): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
V/InputMethodManager( 4621): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
V/InputMethodManager( 4621): b/117267690: Display ID mismatch found. ViewRootImpl displayId=2 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
V/InputMethodManager( 4621): java.lang.Throwable
V/InputMethodManager( 4621): 	at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:549)
V/InputMethodManager( 4621): 	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1625)
V/InputMethodManager( 4621): 	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1617)
V/InputMethodManager( 4621): 	at sH.d(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:3)
V/InputMethodManager( 4621): 	at org.chromium.content.browser.input.ImeAdapterImpl.L(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:20)
V/InputMethodManager( 4621): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:32)
V/InputMethodManager( 4621): 	at android.os.MessageQueue.nativePollOnce(Native Method)
V/InputMethodManager( 4621): 	at android.os.MessageQueue.next(MessageQueue.java:335)
V/InputMethodManager( 4621): 	at android.os.Looper.loopOnce(Looper.java:161)
V/InputMethodManager( 4621): 	at android.os.Looper.loop(Looper.java:288)
V/InputMethodManager( 4621): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
V/InputMethodManager( 4621): 	at java.lang.reflect.Method.invoke(Native Method)
V/InputMethodManager( 4621): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
V/InputMethodManager( 4621): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
W/InputMethodManager( 4621): Ignoring showSoftInput() as view=kr.iamport.iamport_webview_flutter.InputAwareWebView{f65742d VFEDHVC.. .F...... 0,0-1080,1841} is not served.

Flutter 2.5.3 
iamport_flutter: ^0.10.0-dev.6

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.
저희 `0.10.0-dev.6` 예제 앱과 `feature/ui-enhancement` 의 예제 앱에서도 동일하게 발생하시는지요?

**Comment by pavecho** [comment]
넵 동일하게 발생합니다.

**Comment by bungabear** [comment]
동일한 이슈로, webview_flutter의 hybrid composition 관련 사항으로 판단되어,
아래와 같이 적용했습니다.
다만, 저도 다른 side effect가 있는지는 확인을 못했습니다.

```yaml
# pubspec.yaml
iamport_webview_flutter: ^3.0.4
```

```dart
// payment page
import 'package:iamport_webview_flutter/iamport_webview_flutter.dart';
import 'package:iamport_flutter/iamport_payment.dart';


class PaymentPage extends StatefulWidget {
  @override
  State<PaymentPage> createState() => _PaymentPageState();
}

class _PaymentPageState extends State<PaymentPage> {

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) { 
        // TODO apply when Android version >= 12
        WebView.platform = SurfaceAndroidWebView();
    }
  }

  @override
  Widget build(BuildContext context) {
    return OverlayUIStyle(
      navigationBarColor: Common.color.darkBackground,
      child: IamportPayment(),
    );
  }
}
```

**Comment by anymate98** [comment]
해당 문제 해결한 버전 0.10.1 배포했습니다. 문제 해결에 오래 걸려 죄송합니다.

**Comment by pavecho** [comment]
확인했습니다. 해결 감사합니다!
