### ISSUE TITLE
ios에서 iamport가 실행되지 않습니다.

### ISSUE THREAD

**Issue by develop-sell** [iamport/iamport_flutter#56]
flutter version: 1.22.6
dart version: 2.10.5
iamport_flutter version: ^0.9.15

ios 폰에서 0.9.15버전 예제코드 그대로 따라했는데 launch 함수가 없다고 뜨네요.. 

이 아래 순서대로 에러가 걸리는데, 이유를 모르겠습니다. 
### platform_channel.dart 파일
throw MissingPluginException('No implementation found for method $method on channel $name'); // 에러지점

### iamport_url.dart 파일
Future<String> launch() async {
    // [0.9.14] Only for Android
    return await _channel
        .invokeMethod('launch', <String, Object>{'url': this.url}); // 에러지점
  }

### iamport_certification.dart 파일
 IamportUrl iamportUrl = new IamportUrl(url);
bool isOpeningStore = (Platform.isIOS && type == WebViewState.shouldStart) || (Platform.isAndroid && type == WebViewState.abortLoad);
if (isOpeningStore && iamportUrl.isAppLink()) {
    /* Android */
    await iamportUrl.launch(); // 에러 지점
}

## *** 하단은 제가 사용하는 코드입니다. ***
class CertificationScreen extends StatelessWidget {
  const CertificationScreen({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return IamportCertification(
      appBar: new AppBar(
        title: new Text('아임포트 본인인증'),
      ),
      /* 웹뷰 로딩 컴포넌트 */
      initialChild: Container(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                padding: EdgeInsets.fromLTRB(0.0, 30.0, 0.0, 0.0),
                child: Text('잠시만 기다려주세요...', style: TextStyle(fontSize: 20.0)),
              ),
            ],
          ),
        ),
      ),
      /* [필수입력] 가맹점 식별코드 */
      userCode: 'iamport',
      /* [필수입력] 본인인증 데이터 */
      data: CertificationData.fromJson({
        'merchantUid': 'mid_${DateTime.now().millisecondsSinceEpoch}', // 주문번호
        'company': '아임포트', // 회사명 또는 URL
        'carrier': 'SKT', // 통신사
        'name': '홍길동', // 이름
        'phone': '01012341234', // 전화번호
      }),
      /* [필수입력] 콜백 함수 */
      callback: (Map<String, String> result) {
        Navigator.pushReplacementNamed(
          context,
          '/result',
          arguments: result,
        );
      },
    );
  }
}

**Comment by anymate98** [comment]
혹시 flutter clean 후 다시 실행해보셨나요?

**Comment by develop-sell** [comment]
아임포트에 문의드렸는데,
휴대폰 본인인증 서비스는 테스트 모드로 진행되지 않는다는 걸 알게 되었습니다.

기술상의 문제는 아니라서 issue는 닫도록 하겠습니다. 👍🏻
