### ISSUE TITLE
앱 빌드시 assets/images/ 폴더에 있는 파일들이 들어가집니다.

### ISSUE THREAD

**Issue by GwonHyeok** [iamport/iamport_flutter#6]
```
allow-arbitrary.gif
app-scheme-registry.gif
iamport-logo.png
```

앱 빌드시 앱에서 필요로 하지 않는 파일들이 같이 포함되어서 앱 파일용량이 커지는 문제가 있습니다. 
약 17MB를 차지합니다.

확인부탁드립니다.

감사합니다.

<img width="719" alt="스크린샷 2020-02-17 오후 11 49 55" src="https://user-images.githubusercontent.com/3190564/74663987-357b0400-51e0-11ea-9e75-b78b8241c284.png">

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 asset 파일들 중 2개의 gif 파일들은 README에 패키지 연동을 돕고자 포함시킨 것으로 
말씀하신대로 앱을 구동하는데 있어서 필요가 없습니다.
다만, png 파일은 initialChild를 입력하지 않을때 default로 보여주는 이미지이기 때문에
부득이하게 포함시켜야 하지만, 크기가 2.7KB이니 크게 신경쓰실 것 없을 것으로 사료됩니다.

gif 파일들은 패키지 설치지 배제되도록  v0.9.9에 반영하였습니다.
패키지 버전 업그레이드 후 다시 빌드해보시면 iamport-logo.png 파일만 남아있을 겁니다.

제보해주셔서 감사합니다.

**Comment by GwonHyeok** [comment]
@SoleeChoi 확인했습니다. 감사합니다 ~ 👍
