### ISSUE TITLE
이니시스 본인인증 redirect 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by goodmirow-1** [iamport/iamport_flutter#60]
nodejs로 구축한 웹 서버해서 redirect url에서 본인인증 작업후에

 return 값을 날리면 flutter webview에서 흰화면 혹은 return된 값만 뜨고, 아무런 진행이 되지 않습니다.

callback 함수가 호출되지도 않고.. 해결방법이 있을까요?

**Comment by anymate98** [comment]
혹시 웹 서버(웹사이트)에 아임포트 JS SDK 를 사용해 웹사이트만 webview_flutter 등으로 띄운 후 IMP.certification()으로 본인인증을 하셨나요?

**Comment by goodmirow-1** [comment]
아래와 같은 방식으로 redirect url 호출해서 결과값 얻었습니다.

```
app.get("/certifications/redirect", async (req, res) => {
	const { imp_uid } = req.query; // request의 query에서 imp_uid 추출
	try {
		// 인증 토큰 발급 받기
		const getToken = await axios({
		  url: "https://api.iamport.kr/users/getToken",
		  method: "post", // POST method
		  headers: { "Content-Type": "application/json" }, // "Content-Type": "application/json"
		  data: {
			imp_key: "xxxxxxxx", // REST API키
			imp_secret: "xxxxxxxx" // REST API Secret
		  }
		});
		
		const { access_token } = getToken.data.response; // 인증 토큰
		// imp_uid로 인증 정보 조회
		const getCertifications = await axios({
		  url: "https://api.iamport.kr/certifications/" + imp_uid,
		  method: "get", // GET method
		  headers: { "Authorization": access_token } // 인증 토큰 Authorization header에 추가
		});
		const certificationsInfo = getCertifications.data.response; // 조회한 인증 정보
		console.log(certificationsInfo);

		res.redirect('/certifications/check?result=' + true);
	  } catch(e) {
		console.error(e);
		res.redirect('/certifications/check?result=' + false);
	  }
})
```

**Comment by anymate98** [comment]
본인인증 이후 api 조회 과정에 대한 것이군요.
웹사이트 상에서의 작동방식이 정확이 어떻게 되는지 알기가 힘들어 전체적인 작동과정 한번만 설명 부탁드립니다.

**Comment by goodmirow-1** [comment]
넵

flutter 앱에서 다음과 같이 kg이니시스 본인인증을 시행하였습니다.

```
class iamportCertificationPage extends StatefulWidget {
  @override
  _iamportCertificationPageState createState() => _iamportCertificationPageState();
}

class _iamportCertificationPageState extends State<iamportCertificationPage> {
  String userCode = 'impxxxxxxxx';

  CertificationData? data;

  @override
  void initState() {
    data = CertificationData.fromJson({
      'merchantUid': 'mid_${DateTime.now().millisecondsSinceEpoch}', // 주문번호
      'company': 'xxxx', // 회사명 또는 URL
      'm_redirect_url' : ApiProvider().getUrl + '/certifications/redirect'
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle.dark,
      child: ConditionalWillPopScope(
        shouldAddCallbacks: true,
        onWillPop: null,
        child: IamportCertification(
          initialChild: Container(
            child: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Image.asset('assets/image/Login/iamport-logo.png'),
                  Container(
                    padding: EdgeInsets.fromLTRB(0.0, 30.0, 0.0, 0.0),
                    child: Text('잠시만 기다려주세요...', style: TextStyle(fontSize: 20.0)),
                  ),
                ],
              ),
            ),
          ),
          userCode: userCode,
          data: data!,
          callback: (Map<String, String> result) async {
            print(result);
            if (result['success'] == 'true') {
              Get.snackbar('title', '인증 완료!');
              Get.back();
            } else {//본인인증 실패
              Get.snackbar('title', '인증 실패');
              Get.back();
            }
          },
        ),
      ),
    );
  }
}

```

그러고나면 위의 댓글에서 본인인증을 처리하게 되는데,

해당 부분은 아임포트 공식 가이드 페이지에서 참조한 부분입니다.
[(https://docs.iamport.kr/tech/unified-authentication)]
![스크린샷 2022-01-18 오후 5 30 38](https://user-images.githubusercontent.com/57578975/149899621-544db79a-11e3-4ae9-905d-713bb79f454a.png)
위를 참고하여 바로 전 댓글의 코딩을 작성하였으며, 
res.redirect('...') 은 다른 html페이지를 열어 window.close() 코드를 실행하려고 했으나, 그것도 잘 되지 않아서 테스트중인 코드이긴 합니다.

**Comment by anymate98** [comment]
우선 dart 코드에서 본인인증 완료시 snackbar가 잘 뜨는지 궁금합니다.
만약 본인인증이 잘 되었다면, 현재로서는 웹사이트를 다른 웹뷰 객체에서 띄워주시는 것을 권장드립니다.
라이브러리 특성상 url의 변화를 사용자 임의로 조절할 수가 없기 때문에 현재로서는 본인인증을 부른 웹뷰에서 본인인증 및 결제 이후의 작업을 하는 것은 어렵습니다.
따라서 callback을 통해 데이터를 얻을 후에는 새로운 웹뷰(webview_flutter 등)에서 새 페이지 혹은 본인인증 전에 띄워져 있던 기존 페이지에 해당 데이터를 넘기고 작업을 진행하는 것을 추천드립니다.

**Comment by goodmirow-1** [comment]
어.. dart코드에서 callback으로 체크하라셨는데

위의 웹으로 해결하는 작업들은 callback함수가 호출이 안되서 진행한 거였습니다.

debuger를 찍어봐도 중단점이 찍히지 않더라구요.. 

callback 함수가 제대로 호출이 안되는거 자체가 이슈인건가요?

**Comment by anymate98** [comment]
다날은 호출만 하면 됐다는게 어떤 의미인지 궁금합니다.

두가지 콜백이 섞여서 어떤 콜백을 얘기하시는지 모르겠습니다.

위의 자바스크립트 코드는 본인인증 완료 후 m_redirect_url로 리다이렉트 된 후 프론트엔드에서 실행되는 코드겠지요?

라이브러리 차원에서 결제가 끝나면 웹뷰의 내비게이션을 막아놓는데 이것 때문일 수도 있습니다.

**Comment by goodmirow-1** [comment]
아 제가 분석한 dart코드의 다날과 KG이니시스 본인인증의 다른점을 말씀드리겠습니다.

다날의 경우,
위의 dart코드에 m_redirect_url를 제외된 채로 IamportCertification(...) widget을 호출하면 본인인증 작업을 마친 후 callback 함수가 자연스럽게 호출되는 시스템이었는데요,

KG이니시스는
m_redirect_url로 리다이렉트 된 후, 작업이 진행되지 않습니다.  
즉, 위의 dart 코드인
```
callback: (Map<String, String> result) async {
            print(result);
            if (result['success'] == 'true') {
              Get.snackbar('title', '인증 완료!');
              Get.back();
            } else {//본인인증 실패
              Get.snackbar('title', '인증 실패');
              Get.back();
            }
          },
```
이 호출되지 않더라구요. 위의 함수를 호출하기 위해 따로 m_redirect_url로 리다이렉트 된 웹 서버에서 다른 작업을 해야하는지를 물어보는 거였습니다.

**Comment by anymate98** [comment]
현재 iamport_flutter의 m_redirect_url 파라미터에서는 UrlData.redirectUrl 오직 하나만 받아 처리를 할 수 있게 설정되어 있습니다.
따라서 임의의 url을 넣어주시면 결제/본인인증이 끝났는지를 판단할 수 없어 해당 콜백이 실행되지 않습니다.

다날의 경우처럼 m_redirect_url을 넣지 않는 경우에는 자동으로 iframe 모드가 작동하므로 콜백이 실행될 수 있는 것입니다. 만약 임의의 url을 넣는다면 마찬가지로 콜백이 실행되지 않을 것입니다.

**Comment by goodmirow-1** [comment]
넵 설명 감사합니다.

간략하게 dart파일을 좀 수정하여 작업 완료했습니다.
