### ISSUE TITLE
본인인증 웹뷰에서 안드로이드 폰에서 키보드 이슈

### ISSUE THREAD

**Issue by Edward-Kwak** [iamport/iamport_flutter#62]
안녕하세요, 아임포트 본인인증 모듈을 잘 적용하여 사용하던 중,
특정 안드로이드 디바이스에서, 본인인증 웹뷰 상에서 키보드가 나오지 않는 이슈가 생겨 문의드리게 되었습니다.

문제가 발생한 디바이스는 갤럭시 노트 10 - 5G 모델이며, 현재 저는 다날을 통해 본인인증을 구현해 놓은 상태입니다.
다른 디바이스들(노트 8, 갤럭시 s21, 갤럭시 s8, 갤럭시 Jean 등등..)에서는 문제가 없었습니다.

문제가 발생한 디바이스 노트 10 - 5G 모델에서 문제발생 시 화면은 아래와 같습니다.

<img width=320 src=
https://user-images.githubusercontent.com/42112227/151488302-3b52e7fc-5113-4c65-a5ec-26341040511f.png
/>

위 그림과 같이, 본인인증 화면까지는 잘 들어옵니다.

그러나 원래는 위 화면으로 라우팅되는 동시에 키보드가 같이 올라와야 하지만,
문제가 발생한 노트 10 기기에서는 키보드가 올라오지 않으며,
이름이나 다른 입력란의 텍스트 필드를 아무리 터치해도 반응이 없었습니다.

그러나 위 웹뷰의 우상단 x 표 닫기 버튼은 터치에 반응하여 화면이 잘 닫히며,
제가 따로 마련한 Appbar의 뒤로가기 버튼도 아무 이상없이 잘 동작합니다.

웹뷰의 텍스트 필드와 그 외에 pass 설치하기 및 문자 sms 인증 버튼 또한 아무런 반응이 없습니다.

추가로 확인한 점은, 문제가 발생했던 노트 10 기기에서,
이번에는 Nice를 통해 본인인증을 구현한 다른 앱에서는, 아래 그림과 같이 본인인증 화면에서 잘 작동합니다.

<img width=320 src=https://user-images.githubusercontent.com/42112227/151489445-9cf72982-e08c-4997-a03a-568231646cb8.png />

혹시 이 문제와 관련하여, 아임포트 측에서 도움을 주실수 있을까하여 문의드려봅니다.

감사합니다.

추신)
(flutter에서는 IamportCertification 함수를 통해 본인인증 웹뷰를 띄우고 있습니다.
문제가 발생한 갤럭시 노트 10 디바이스는 삼성 기본 키보드를 사용하고 있습니다.)

**Comment by anymate98** [comment]
무슨 버전 사용하고 계시는지 알 수 있을까요?

**Comment by Edward-Kwak** [comment]
답변이 늦어 죄송합니다.

현재 0.10.0-dev.6 버전을 사용중입니다!

**Comment by anymate98** [comment]
0.10.1에서 문제 해결되었는데 업데이트하시면 정상적으로 이용 가능하실 것 같습니다.

**Comment by Edward-Kwak** [comment]
0.10.1로 업데이트 후, 정상작동 확인했습니다!

감사합니다. :)
