### ISSUE TITLE
결제 환불 처리 방법 문의

### ISSUE THREAD

**Issue by ctrlcv** [iamport/iamport_flutter#68]
안녕하세요...

iamport_flutter 에 결제 환불 처리 방법이 있는지 문의 드립니다.
예제코드에서 결제 처리와 본인 인증은 확인하였지만 결제 환불 처리방법은 찾지 못해 문의 드립니다.

혹시 이미 있는데 제가 못 찾은 거라면 함수명이라도 알려주시면 감사드리겠습니다.

**Comment by anymate98** [comment]
결제 환불은 [아임포트 api](https://api.iamport.kr) 및 관리자 콘솔을 통해 진행해주시면 됩니다.
