### ISSUE TITLE
휴대폰 본인인증 성공 후 인증 정보 취득

### ISSUE THREAD

**Issue by developtkr** [iamport/iamport_flutter#7]
안녕하세요 iamport_flutter 본인인증 모듈을 활용하여 서비스를 개발하려 하고 있습니다.
본인인증 모듈을 테스트를 성공했습니다. flutter 모듈 제공에 감사드립니다.

추가적으로 궁금한 점이 있어서 문의 드립니다.
https://docs.iamport.kr/tech/mobile-authentication

휴대폰 본인인증 연동하기 ->  STEP-5. 서버에서 인증 조회하기
문서에서 확인해보면,
인증 성공 후 인증 정보 취득을 요청하여 성별/생년 정보 등을 받아올 수 있는 문서를 확인했는데
flutter 모듈에서는 이에 대한 가이드가 없어서
혹시 추가적인 개발 계획이나, 취득 가능한 방법에 대해 알려주시면 정말 감사하겠습니다.

감사합니다.

**Comment by developtkr** [comment]
imp_uid 획득 후 가이드를 보고 Rest api로 호출하는 별도 모듈을 직접 개발해야할까요?

**Comment by jangbora** [comment]
네 맞습니다. 별도로 개발을 해주셔야 합니다. imp_uid 획득 후 REST API 로 상세 조회하는 기능은 운영하시는 서버단에서 수행하여야 하므로 flutter 예제에는 포함되어있지 않습니다. 
사용하시는 백엔드 프로그래밍 언어가 어떻게 되시나요?

**Comment by developtkr** [comment]
백엔드는 주로 php를 사용하고 있고, 인증 관련해서 현재 작업된 내용은 없습니다 ㅠ

**Comment by developtkr** [comment]
오 php는 이런 연동모듈도 제공하고계시군요?

https://github.com/iamport/iamport-rest-client-php

**Comment by jangbora** [comment]
네 맞습니다. 해당 프로젝트의 소스코드와 예제를 참고하여 구현하시면 보다 쉽게 구현이 가능합니다.

**Comment by developtkr** [comment]
답변 감사합니다!
