### ISSUE TITLE
[flutter] 결제 후 콜백 result 값 

### ISSUE THREAD

**Issue by Godrl** [iamport/iamport_flutter#72]
현재 앱 빌드 후 결제테스트 진행중입니다.

결제 성공 후 주문완료 처리를 위해 callback result 값을 넘겨주는데요 
웹버전에서는 buyer_addr, buyer_email, buyer_name 등등 의 값들이 넘어오는데
flutter 에서는 imp_uid, merchant_uid, imp_success 값들만 넘어옵니다.

flutter 에서는 저 값들만 결과로 받을수 있는건지 아니라면 어떻게해야 다른 속성들도 받을 수 있는지 답변부탁드립니다!

**Comment by anymate98** [comment]
웹버전에서 받으신 정보들은 iframe 모드에서 콜백을 통해 받으신 것들입니다. 그러나 모바일의 경우 대부분 리다이렉트 방식으로 작동하고 따라서 결과를 url 뒤에 붙이고 있습니다. 그러나 url에는 길이 제한이 있으므로 buyer_addr과 같은 정보를 표현하기에는 공간이 부족해 저 필수 정보들만 보내주고 있습니다.
iamport_flutter에서 콜백으로 받는 정보들은 실제 콜백이 아니고 저 리다이렉트 url을 파싱한 결과물입니다. 따라서 정보가 제한될 수 밖에 없습니다.
현재 상황에서 추가적으로 정보를 얻기 위해서는 아임포트 REST API를 사용하시면 될 것 같습니다.

**Comment by Godrl** [comment]
넵 답변 감사합니다!
