### ISSUE TITLE
app build error: A problem occurred configuring project ':uni_links'.

### ISSUE THREAD

**Issue by Godrl** [iamport/iamport_flutter#73]
flutter build appbundle 명령어로 앱 빌드를 하려고 하는데 오류가 발생합니다.
iamport 에서 사용되는 uni_links 라는 패키지로 확인이 되는데 이유가 무엇인지 확인 부탁드립니다!!

아래는 에러 내용입니다.
--------------------------------------------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':uni_links'.
> Could not resolve all artifacts for configuration ':uni_links:classpath'.
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.50.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.50/kotlin-stdlib-jdk8-1.3.50.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.lint:lint-gradle-api:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:gradle-api:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:common:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:manifest-merger:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.analytics-library:tracker:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4 > com.android.tools.analytics-library:shared:26.5.4
   > Could not find org.ow2.asm:asm:6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/ow2/asm/asm/6.0/asm-6.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
   > Could not find org.ow2.asm:asm-analysis:6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-analysis/6.0/asm-analysis-6.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
   > Could not find org.ow2.asm:asm-commons:6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-commons/6.0/asm-commons-6.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
   > Could not find org.ow2.asm:asm-util:6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-util/6.0/asm-util-6.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
   > Could not find net.sf.jopt-simple:jopt-simple:4.9.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
   > Could not find net.sf.proguard:proguard-gradle:6.0.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/net/sf/proguard/proguard-gradle/6.0.3/proguard-gradle-6.0.3.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
   > Could not find com.google.protobuf:protobuf-java:3.4.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:bundletool:0.9.0
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.analytics-library:protos:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.analytics-library:tracker:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:bundletool:0.9.0 > com.android.tools.build:aapt2-proto:0.4.0
   > Could not find com.google.protobuf:protobuf-java-util:3.4.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/protobuf/protobuf-java-util/3.4.0/protobuf-java-util-3.4.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:bundletool:0.9.0
   > Could not find com.squareup:javawriter:2.5.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/squareup/javawriter/2.5.0/javawriter-2.5.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
   > Could not find org.bouncycastle:bcpkix-jdk15on:1.56.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:apkzlib:3.5.4
   > Could not find org.bouncycastle:bcprov-jdk15on:1.56.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:apkzlib:3.5.4
   > Could not find org.ow2.asm:asm-tree:6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-tree/6.0/asm-tree-6.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
   > Could not find javax.inject:javax.inject:1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/javax/inject/javax.inject/1/javax.inject-1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
   > Could not find it.unimi.dsi:fastutil:7.2.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
   > Could not find com.googlecode.json-simple:json-simple:1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/googlecode/json-simple/json-simple/1.1/json-simple-1.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
   > Could not find com.google.guava:guava:27.0.1-jre.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.analytics-library:crash:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.lint:lint-gradle-api:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:gradle-api:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:bundletool:0.9.0
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:common:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.analytics-library:tracker:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4 > com.android.tools.analytics-library:shared:26.5.4
   > Could not find org.apache.httpcomponents:httpmime:4.5.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/apache/httpcomponents/httpmime/4.5.6/httpmime-4.5.6.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.analytics-library:crash:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4
   > Could not find org.apache.httpcomponents:httpcore:4.4.10.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.analytics-library:crash:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4
   > Could not find org.apache.httpcomponents:httpclient:4.5.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.analytics-library:crash:26.5.4
   > Could not find org.jetbrains.kotlin:kotlin-reflect:1.3.50.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.50/kotlin-reflect-1.3.50.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.lint:lint-gradle-api:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
   > Could not find org.antlr:antlr4:4.5.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/antlr/antlr4/4.5.3/antlr4-4.5.3.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
   > Could not find commons-io:commons-io:2.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/commons-io/commons-io/2.4/commons-io-2.4.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
   > Could not find com.googlecode.juniversalchardet:juniversalchardet:1.0.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
   > Could not find com.squareup:javapoet:1.8.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/squareup/javapoet/1.8.0/javapoet-1.8.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
   > Could not find com.google.code.gson:gson:2.8.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:manifest-merger:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4 > com.android.tools.analytics-library:shared:26.5.4
   > Could not find com.google.auto.value:auto-value:1.5.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:bundletool:0.9.0
   > Could not find com.google.errorprone:error_prone_annotations:2.3.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/errorprone/error_prone_annotations/2.3.1/error_prone_annotations-2.3.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:bundletool:0.9.0
   > Could not find com.google.code.gson:gson:2.8.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-core:1.0.0-beta04
   > Could not find org.jetbrains.kotlin:kotlin-stdlib:1.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.0/kotlin-stdlib-1.3.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-core:1.0.0-beta04
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
   > Could not find org.jdom:jdom2:2.0.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jdom/jdom2/2.0.6/jdom2-2.0.6.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
   > Could not find org.apache.commons:commons-compress:1.12.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/apache/commons/commons-compress/1.12/commons-compress-1.12.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4
   > Could not find org.jetbrains.trove4j:trove4j:20160824.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
   > Could not find net.sf.kxml:kxml2:2.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:manifest-merger:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.ddms:ddmlib:26.5.4
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools.layoutlib:layoutlib-api:26.5.4
   > Could not find com.google.code.findbugs:jsr305:1.3.9.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:apkzlib:3.5.4
   > Could not find com.google.guava:guava:27.0.1-jre.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:apkzlib:3.5.4
   > Could not find org.jetbrains:annotations:13.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/annotations/13.0/annotations-13.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools.layoutlib:layoutlib-api:26.5.4
   > Could not find com.sun.activation:javax.activation:1.2.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4
   > Could not find org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4
   > Could not find com.google.jimfs:jimfs:1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/jimfs/jimfs/1.1/jimfs-1.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :uni_links > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4

**Comment by anymate98** [comment]
원인으로 의심되는 것이 여러개 있어서 특정하기 힘든데
flutter clean 후 다시 시도해보셨나요?
또한 build.gradle에 google maven repository가 잘 들어가 있는지도 확인해봐야 할 것 같습니다.

**Comment by Godrl** [comment]
플러터 설치한 경로에서 flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1 폴더를 삭제 후 다시 pub get 명령어 실행 후 빌드 하니 수정되었습니다!
