### ISSUE TITLE
json_annotation ^4.5.0 지원

### ISSUE THREAD

**Issue by SuhwanCha** [iamport/iamport_flutter#79]
안녕하세요,
현재 0.10.1+3 버전에서 json_annotation ^4.5.0을 지원하지 않고 있습니다.

https://github.com/iamport/iamport_flutter/blob/1e42e0503bd6eaf6649686fbdcaa305eb7d0c432/pubspec.yaml#L16

json_annotation 4.5.0에서도 사용 가능하게 하도록 업데이트가 예정되어 있나요?

저희는 현재 프로젝트에서 json_annotation 4.5.0을 사용 중인데, iamport_flutter 설치시 json_annotation 버전 때문에 `^0.10.0-dev.6` 버전으로 밖에 설치가 안되다보니 기능이 정상적으로 작동하지 않는 이슈가 발생하고 있습니다.

**Comment by anymate98** [comment]
제약조건 완화하여 v0.10.1+4 배포했습니다.
