### ISSUE TITLE
Kotlin Gradle Plugin 업데이트 일정 문의 드립니다.

### ISSUE THREAD

**Issue by jungsangeun** [iamport/iamport_flutter#93]
현재 1.3.50 을 사용하고 계신 것으로 보여지는데요.
혹시 최신 버전으로 업데이트 일정이 있으신지 확인 부탁드립니다.

**Comment by anymate98** [comment]
안녕하세요. 코틀린 버전을 1.7.20으로 올려 배포했으니 확인 부탁드립니다.

**Comment by jungsangeun** [comment]
감사합니다!!
새해 복 다 받으세요!!
